decode_logement_neuf = {
"o": "Oui",
"n": "Non"
}

decode_typedebien = {
"m":"Maison/Villa",
"ch":"Château",
"a":"Appartement",
"bu":"Bureau",
"h":"Hôtel particulier",
"mn":"Maison / Villa neuve",
"mn":"TerrainAvecMaison",
"l":"Loft/Atelier",
"d":"Divers",
"l":"Loft/Atelier/Surface",
"m":"Maison / Villa",
"bou":"Boutique",
"p":"Parking",
"ba":"Bâtiment",
"i":"Immeuble",
"t":"Terrain",
"an":"Appartement neuf",
"lc":"Local commercial"
}


decode_typedetransaction = {
"cdb":"Cession de bail",
"np":"Nue-propriété",
"pi":"Produit d’investissement",
"vfc":"Vente fonds de commerce",
"vp":"Vente de prestige",
"lt":"Location temporaire",
"l":"Location",
"v":"Vente",
"lv":"Location vacances",
"pi":"Produit d'investissement",
"vi":"Viager"
}

decode_categorie_annonceur = {
"a":"Agence",
"b":"broker",
"ca":"Constructeur appartements",
"cm":"Constructeur maisons",
"m":"Mandataire"
}



const array_decode_fields = [
	{logement_neuf: {
	"o": "Oui",
	"n": "Non"}
	},

	{typedebien: {
	"m":"Maison/Villa",
	"ch":"Château",
	"a":"Appartement",
	"bu":"Bureau",
	"h":"Hôtel particulier",
	"mn":"Maison / Villa neuve",
	"mn":"TerrainAvecMaison",
	"l":"Loft/Atelier",
	"d":"Divers",
	"l":"Loft/Atelier/Surface",
	"m":"Maison / Villa",
	"bou":"Boutique",
	"p":"Parking",
	"ba":"Bâtiment",
	"i":"Immeuble",
	"t":"Terrain",
	"an":"Appartement neuf",
	"lc":"Local commercial"}
	},


	{typedetransaction: {
	"cdb":"Cession de bail",
	"np":"Nue-propriété",
	"pi":"Produit d’investissement",
	"vfc":"Vente fonds de commerce",
	"vp":"Vente de prestige",
	"lt":"Location temporaire",
	"l":"Location",
	"v":"Vente",
	"lv":"Location vacances",
	"pi":"Produit d'investissement",
	"vi":"Viager"}
	},

	{categorie_annonceur: {
	"a":"Agence",
	"b":"broker",
	"ca":"Constructeur appartements",
	"cm":"Constructeur maisons",
	"m":"Mandataire"}
	}
]


var encoded_fields = [
	{source_ref: 'annonces_ventes', logement_neuf: 'o', lib_logement_neuf: 'Neuf'},
	{source_ref: 'annonces_ventes', logement_neuf: 'n', lib_logement_neuf: 'Ancien'},
	{source_ref: 'annonces_ventes', typedebien:  "m", lib_typedebien: "Maison/Villa"},
	{source_ref: 'annonces_ventes', typedebien:  "ch", lib_typedebien: "Château"},
	{source_ref: 'annonces_ventes', typedebien:  "a", lib_typedebien: "Appartement"},
	{source_ref: 'annonces_ventes', typedebien:  "bu", lib_typedebien: "Bureau"},
	{source_ref: 'annonces_ventes', typedebien:  "h", lib_typedebien: "Hôtel particulier"},
	{source_ref: 'annonces_ventes', typedebien: "mn", lib_typedebien: "Maison / Villa neuve"},
	{source_ref: 'annonces_ventes', typedebien: "mn", lib_typedebien: "TerrainAvecMaison"},
	{source_ref: 'annonces_ventes', typedebien:  "l", lib_typedebien: "Loft/Atelier"},
	{source_ref: 'annonces_ventes', typedebien:  "d", lib_typedebien: "Divers"},
	{source_ref: 'annonces_ventes', typedebien:  "l", lib_typedebien: "Loft/Atelier/Surface"},
	{source_ref: 'annonces_ventes', typedebien:  "m", lib_typedebien: "Maison / Villa"},
	{source_ref: 'annonces_ventes', typedebien: "bou", lib_typedebien: "Boutique"},
	{source_ref: 'annonces_ventes', typedebien:  "p", lib_typedebien: "Parking"},
	{source_ref: 'annonces_ventes', typedebien:  "ba", lib_typedebien: "Bâtiment"},
	{source_ref: 'annonces_ventes', typedebien:  "i", lib_typedebien: "Immeuble"},
	{source_ref: 'annonces_ventes', typedebien:  "t", lib_typedebien: "Terrain"},
	{source_ref: 'annonces_ventes', typedebien:  "an", lib_typedebien: "Appartement neuf"},
	{source_ref: 'annonces_ventes', typedebien: "lc", lib_typedebien: "Local commercial"},
	{source_ref: 'annonces_ventes', typedetransaction: "cdb", lib_typedetransaction: "Cession de bail"},
	{source_ref: 'annonces_ventes', typedetransaction: "np", lib_typedetransaction: "Nue-propriété"},
	{source_ref: 'annonces_ventes', typedetransaction: "pi", lib_typedetransaction: "Produit d’investissement"},
	{source_ref: 'annonces_ventes', typedetransaction: "vfc", lib_typedetransaction: "Vente fonds de commerce"},
	{source_ref: 'annonces_ventes', typedetransaction: "vp", lib_typedetransaction: "Vente de prestige"},
	{source_ref: 'annonces_ventes', typedetransaction: "lt", lib_typedetransaction: "Location temporaire"},
	{source_ref: 'annonces_ventes', typedetransaction: "l", lib_typedetransaction: "Location"},
	{source_ref: 'annonces_ventes', typedetransaction: "v", lib_typedetransaction: "Vente"},
	{source_ref: 'annonces_ventes', typedetransaction: "lv", lib_typedetransaction: "Location vacances"},
	{source_ref: 'annonces_ventes', typedetransaction: "pi", lib_typedetransaction: "Produit d'investissement"},
	{source_ref: 'annonces_ventes', typedetransaction: "vi", lib_typedetransaction: "Viager"},
	{source_ref: 'annonces_ventes', categorie_annonceur: "a", lib_categorie_annonceur: "Agence"},
	{source_ref: 'annonces_ventes', categorie_annonceur: "b", lib_categorie_annonceur: "broker"},
	{source_ref: 'annonces_ventes', categorie_annonceur: "ca", lib_categorie_annonceur: "Constructeur appartements"},
	{source_ref: 'annonces_ventes', categorie_annonceur: "cm", lib_categorie_annonceur: "Constructeur maisons"},
	{source_ref: 'annonces_ventes', categorie_annonceur: "m", lib_categorie_annonceur: "Mandataire"},
	{source_ref: 'annonces_ventes', categorie_annonceur: "cdb", lib_categorie_annonceur: "Cession de bail"},
	{source_ref: 'annonces_ventes', nb_pieces: 1, lib_nb_pieces: "un"},
	{source_ref: 'annonces_ventes', nb_pieces: 2, lib_nb_pieces: "deux"},
	{source_ref: 'annonces_ventes', nb_pieces: 3, lib_nb_pieces: "trois"},
	{source_ref: 'annonces_ventes', nb_pieces: 4, lib_nb_pieces: "quatre"},
	{source_ref: 'annonces_ventes', nb_pieces: 5, lib_nb_pieces: "cinq"},
	{source_ref: 'annonces_ventes', nb_pieces: 6, lib_nb_pieces: "six"},
	{source_ref: 'annonces_ventes', nb_pieces: 7, lib_nb_pieces: "sept"},
	{source_ref: 'annonces_ventes', nb_pieces: 8, lib_nb_pieces: "huit"},
	// {source_ref: 'sitadel', CAT_MOA: 10, lib_CAT_MOA:'Particuliers sans autre indication (SAI)'},
	// {source_ref: 'sitadel', CAT_MOA: 11, lib_CAT_MOA: 'Particuliers purs'},
	// {source_ref: 'sitadel', CAT_MOA: 12 , lib_CAT_MOA: "SCI de particuliers"},
	// {source_ref: 'sitadel', CAT_MOA: 20, lib_CAT_MOA: "Bailleurs sociaux SAI"},
	// {source_ref: 'sitadel', CAT_MOA: 21, lib_CAT_MOA: "Organismes HLM"},
	// {source_ref: 'sitadel', CAT_MOA: 22, lib_CAT_MOA: "EPL (ex SEM)"},
	// {source_ref: 'sitadel', CAT_MOA: 23, lib_CAT_MOA: "Autres organismes"},
	// {source_ref: 'sitadel', CAT_MOA: 30, lib_CAT_MOA: "Promoteurs (SAI)"},
	// {source_ref: 'sitadel', CAT_MOA: 31, lib_CAT_MOA: "Promoteurs reconnus comme tels"},
	// {source_ref: 'sitadel', CAT_MOA: 32, lib_CAT_MOA: "SCI ou autres supports de programmes de construction"},
	// {source_ref: 'sitadel', CAT_MOA: 33, lib_CAT_MOA: "Autres professionnels de la construction"},
	// {source_ref: 'sitadel', CAT_MOA: 40, lib_CAT_MOA: "Administrations publiques (SAI)"},
	// {source_ref: 'sitadel', CAT_MOA: 41, lib_CAT_MOA: "État, ODAC (Organismes Divers d'Administration Centrale) et organismes rattachés divers"},
	// {source_ref: 'sitadel', CAT_MOA: 42, lib_CAT_MOA: "Départements et régions"},
	// {source_ref: 'sitadel', CAT_MOA: 43, lib_CAT_MOA: "Communes, EPIC, syndicats de communes"},
	// {source_ref: 'sitadel', CAT_MOA: 50, lib_CAT_MOA: "Autres sociétés (de fait, intervenant pour compte propre)"},
	// {source_ref: 'sitadel', CAT_MOA: 80, lib_CAT_MOA: "Sans objet (car locaux purs)"},
	// {source_ref: 'sitadel', CAT_MOA: 90, lib_CAT_MOA: "Non déterminé (valeur par défaut à la création du permis)"},
	{source_ref: 'sitadel', CAT_MOA: 10, lib_CAT_MOA:'Particuliers (cat 10)'},
	{source_ref: 'sitadel', CAT_MOA: 11, lib_CAT_MOA: 'Particuliers purs'},
	{source_ref: 'sitadel', CAT_MOA: 12 , lib_CAT_MOA: "SCI de particuliers"},
	{source_ref: 'sitadel', CAT_MOA: 20, lib_CAT_MOA: "Bailleurs sociaux SAI"},
	{source_ref: 'sitadel', CAT_MOA: 21, lib_CAT_MOA: "Organismes HLM"},
	{source_ref: 'sitadel', CAT_MOA: 22, lib_CAT_MOA: "EPL (ex SEM)"},
	{source_ref: 'sitadel', CAT_MOA: 23, lib_CAT_MOA: "Autres organismes"},
	{source_ref: 'sitadel', CAT_MOA: 30, lib_CAT_MOA: "Promoteurs (SAI)"},
	{source_ref: 'sitadel', CAT_MOA: 31, lib_CAT_MOA: "Promoteurs... (cat 31)"},
	{source_ref: 'sitadel', CAT_MOA: 32, lib_CAT_MOA: "SCI... (cat 32)"},
	{source_ref: 'sitadel', CAT_MOA: 33, lib_CAT_MOA: "Autres... (cat 33)"},
	{source_ref: 'sitadel', CAT_MOA: 40, lib_CAT_MOA: "Administrations pub."},
	{source_ref: 'sitadel', CAT_MOA: 41, lib_CAT_MOA: "État, ODAC... (cat 41)"},
	{source_ref: 'sitadel', CAT_MOA: 42, lib_CAT_MOA: "Départements et régions"},
	{source_ref: 'sitadel', CAT_MOA: 43, lib_CAT_MOA: "Communes, EPIC... (cat 43)"},
	{source_ref: 'sitadel', CAT_MOA: 50, lib_CAT_MOA: "Autres sociétés...(cat 50)"},
	{source_ref: 'sitadel', CAT_MOA: 80, lib_CAT_MOA: "Sans objet (cat 80)"},
	{source_ref: 'sitadel', CAT_MOA: 90, lib_CAT_MOA: "Non déterminé (cat 90)"},	
	{source_ref: 'sitadel', TYPE_EVT: 1, lib_TYPE_EVT: "dépôt"},
	{source_ref: 'sitadel', TYPE_EVT: 2 , lib_TYPE_EVT: "autorisation"},
	{source_ref: 'sitadel', TYPE_EVT: 3, lib_TYPE_EVT: "travaux commencés"},
	{source_ref: 'sitadel', NATURE_PROJET: 1, lib_NATURE_PROJET: "nouvelle construction"},
	{source_ref: 'sitadel', NATURE_PROJET: 2, lib_NATURE_PROJET: "construction sur existant"},
	{source_ref: 'sitadel', NATURE_PROJET: 3, lib_NATURE_PROJET : "const. nvlle et sur const. existante"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 1, lib_TYPE_OPERATION_CONSTR: "Projets sans mouv. de surface"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 2, lib_TYPE_OPERATION_CONSTR: "Démolition simple"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 3, lib_TYPE_OPERATION_CONSTR: "Démolitions multiples"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 4, lib_TYPE_OPERATION_CONSTR: "Agrand. de logt existant"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 5, lib_TYPE_OPERATION_CONSTR: "Const. d'une maison indiv"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 6, lib_TYPE_OPERATION_CONSTR: "Const. de logts en résidences"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 7, lib_TYPE_OPERATION_CONSTR: "Autre const. de logements"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 8, lib_TYPE_OPERATION_CONSTR: "Const. de locaux"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 9, lib_TYPE_OPERATION_CONSTR: "Transform. de logements en locaux"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 10, lib_TYPE_OPERATION_CONSTR: "Transform. de locaux en logts"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 11, lib_TYPE_OPERATION_CONSTR: "Transform. de locaux"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 12, lib_TYPE_OPERATION_CONSTR: "Autres opérations (habitation)"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 13, lib_TYPE_OPERATION_CONSTR: "Autres opérations (locaux)"},
	{source_ref: 'sitadel', TYPE_OPERATION_CONSTR: 14, lib_TYPE_OPERATION_CONSTR: "Autres opérations de const."},

	

]

let arr_poi_to_display_old = [
	"A101",
	"A104",
	"A203",
	"A206",
	"A207",
	"A208",
	"A501",
	"A502",
	"A504",
	"B101",
	"B102",
	"B201",
	"B202",
	"B203",
	"B204",
	"B205",
	"B206",
	"B301",
	"B302",
	"B316",
	"C101",
	"C102",
	"C104",
	"C105",
	"C201",
	"C301",
	"C302",
	"C303",
	"C304",
	"C305",
	"C401",
	"C402",
	"C403",
	"C409",
	"C501",
	"C502",
	"C503",
	"C504",
	"C505",
	"C509",
	"C601",
	"C701",
	"D101",
	"D102",
	"D103",
	"D106",
	"D107",
	"D108",
	"D110",
	"D112",
	"D113",
	"D201",
	"D202",
	"D203",
	"D206",
	"D208",
	"D209",
	"D210",
	"D211",
	"D212",
	"D213",
	"D214",
	"D231",
	"D232",
	"D233",
	"D235",
	"D237",
	"D238",
	"D242",
	"D243",
	"D301",
	"D303",
	"D305",
	"D502",
	"E102",
	"F101",
	"F103",
	"F105",
	"F106",
	"F107",
	"F108",
	"F109",
	"F111",
	"F112",
	"F113",
	"F114",
	"F118",
	"F120",
	"F121",
	"F201",
	"F202",
	"F203",
	"F303",
	"F304",
	"F305",
	"F306",
	"F307",
	"G102",
];


let arr_poi_to_display = [
	"A101",
	"A104",
	"A203",
	"A206",
	"A207",
	"A208",
	"A504",
	"B101",
	"B102",
	"B201",
	"B202",
	"B203",
	"B204",
	"B205",
	"B206",
	"B301",
	"C101",
	"C102",
	"C104",
	"C105",
	"C201",
	"C301",
	"C302",
	"D106",
	"D107",
	"D108",
	"D110",
	"D112",
	"D113",
	"D201",
	"D232",
	"D233",
	"D301",
	"D502",
	"E102",
	"F101",
	"F102",
	"F103",
	"F104",
	"F105",
	"F106",
	"F107",
	"F108",
	"F109",
	"F111",
	"F112",
	"F113",
	"F114",
	"F118",
	"F120",
	"F121",
	"F201",
	"F202",
	"F203",
	"F303",
	"F304",
	"F305",
	"F306",
	"F307",
	"G102",
	"Transport public"
]